version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: leadgogo
    volumes:
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - 5672:5672
      # - '$RABBITMQ_MANAGEMENT_PORT:15672'
